name: Deploy stage

on:
  push:
    branches: [hand/stage__]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:development

      - name: Deploy
        uses: jakejarvis/s3-sync-action@master
        env:
          SOURCE_DIR: 'build'
          AWS_REGION: 'ap-northeast-2'
          AWS_S3_BUCKET: 'definix-frontend'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_HAND_STAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_HAND_STAGE_SECRET_ACCESS_KEY }}
      - name: invalidate
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_HAND_STAGE_FRONTEND_DISTRIBUTION_ID }}
          PATHS: '/*'
          AWS_REGION: 'ap-northeast-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_HAND_STAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_HAND_STAGE_SECRET_ACCESS_KEY }}
